# Generated by Django 2.2 on 2019-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=40)),
            ],
        ),
    ]
