# Generated by Django 2.2 on 2019-04-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_auto_20190421_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='imglink',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
