# Generated by Django 2.2 on 2019-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_item_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
